version: '3.1'

services:
  fibos:
    # build: ./fibos
    image: mingfunwong/fibos:v1.7.1.2
    restart: always
    container_name: fibos-node
    stop_grace_period: 10m
    ports:
      - 8888:8888
      - 9977:9876
    volumes:
      - ./_data_fibos:/fibos/data
      - /snapshots:/fibos/data/snapshots
      - ./fibos/genesis.json:/fibos/genesis.json
      - ./fibos/start.js:/fibos/start.js
      - ./fibos/p2p.json:/fibos/p2p.json
    command: ["fibos", "/fibos/start.js"]

  api:
    # build: ./api
    image: mingfunwong/fibos:api.fibos123.com
    restart: always
    links: 
      - fibos
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./_data_api:/api/data
      - ./api/_config.js:/api/_config.js
      - ./api/index.js:/api/index.js
      - ./api/lib:/api/lib

  caddy:
    image: abiosoft/caddy
    restart: always
    links: 
      - fibos
      - api
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile
