version: '2'

services:
  api.fibos123.com:
    image: mingfunwong/api.fibos123.com
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      FIBOS_RPC_ENDPOINT: ${FIBOS_RPC_ENDPOINT}
